services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Load your custom nginx config
      - ../public:/public  # Mount the public directory correctly
      - ../app:/app  # Mount the app directory

  app:
    build:
      context: ..  # Context should be the parent directory
      dockerfile: docker/Dockerfile  # Path to your Dockerfile
    volumes:
      - ../app:/app  # Mount the app directory
      - ../public:/public  # Mount the public directory correctly
    expose:
      - "9000"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}
